# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/chernomirdinmacuvele/Documents/workspace/File_MX_EE/UI/ui_Documento.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(562, 525)
        self.gridLayout_3 = QtWidgets.QGridLayout(Form)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.DEData = QtWidgets.QDateEdit(Form)
        self.DEData.setAlignment(QtCore.Qt.AlignCenter)
        self.DEData.setObjectName("DEData")
        self.gridLayout_2.addWidget(self.DEData, 1, 2, 1, 2)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.CBType = QtWidgets.QComboBox(Form)
        self.CBType.setObjectName("CBType")
        self.horizontalLayout.addWidget(self.CBType)
        self.settingsButton = QtWidgets.QPushButton(Form)
        self.settingsButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.settingsButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../File_Mx/res/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingsButton.setIcon(icon)
        self.settingsButton.setFlat(False)
        self.settingsButton.setObjectName("settingsButton")
        self.horizontalLayout.addWidget(self.settingsButton)
        self.gridLayout_2.addLayout(self.horizontalLayout, 3, 0, 1, 4)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 2)
        self.SBCod = QtWidgets.QSpinBox(Form)
        self.SBCod.setAlignment(QtCore.Qt.AlignCenter)
        self.SBCod.setReadOnly(True)
        self.SBCod.setMaximum(1000)
        self.SBCod.setObjectName("SBCod")
        self.gridLayout_2.addWidget(self.SBCod, 0, 2, 1, 2)
        self.PBClose = QtWidgets.QPushButton(Form)
        self.PBClose.setObjectName("PBClose")
        self.gridLayout_2.addWidget(self.PBClose, 7, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 6, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(73, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 7, 1, 1, 2)
        self.PBSave = QtWidgets.QPushButton(Form)
        self.PBSave.setObjectName("PBSave")
        self.gridLayout_2.addWidget(self.PBSave, 7, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 1, 1, 1)
        self.PBRemove = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PBRemove.sizePolicy().hasHeightForWidth())
        self.PBRemove.setSizePolicy(sizePolicy)
        self.PBRemove.setMinimumSize(QtCore.QSize(51, 0))
        self.PBRemove.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.PBRemove.setFont(font)
        self.PBRemove.setObjectName("PBRemove")
        self.gridLayout.addWidget(self.PBRemove, 2, 2, 1, 1)
        self.LWPaths = QtWidgets.QListWidget(Form)
        self.LWPaths.setObjectName("LWPaths")
        self.gridLayout.addWidget(self.LWPaths, 1, 0, 1, 3)
        self.PBAdd = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PBAdd.sizePolicy().hasHeightForWidth())
        self.PBAdd.setSizePolicy(sizePolicy)
        self.PBAdd.setMinimumSize(QtCore.QSize(51, 0))
        self.PBAdd.setMaximumSize(QtCore.QSize(100, 16777215))
        self.PBAdd.setObjectName("PBAdd")
        self.gridLayout.addWidget(self.PBAdd, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 4, 8, 1)
        self.CBToStore = QtWidgets.QComboBox(Form)
        self.CBToStore.setObjectName("CBToStore")
        self.gridLayout_2.addWidget(self.CBToStore, 2, 0, 1, 4)
        self.PTEInfo = QtWidgets.QPlainTextEdit(Form)
        self.PTEInfo.setObjectName("PTEInfo")
        self.gridLayout_2.addWidget(self.PTEInfo, 4, 0, 2, 4)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Documento"))
        self.DEData.setDisplayFormat(_translate("Form", "dd/MM/yyyy"))
        self.label_3.setText(_translate("Form", "Data dos Ficheiros"))
        self.label_4.setText(_translate("Form", "Nº do Registo"))
        self.PBClose.setText(_translate("Form", "Fechar"))
        self.PBSave.setText(_translate("Form", "Guardar"))
        self.label.setText(_translate("Form", "Ficheiros"))
        self.PBRemove.setText(_translate("Form", "Remover"))
        self.PBAdd.setText(_translate("Form", "Adicionar"))
        self.PTEInfo.setPlaceholderText(_translate("Form", "Informacão extra"))

