# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_Main.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(768, 590)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.PBConfigurar = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PBConfigurar.sizePolicy().hasHeightForWidth())
        self.PBConfigurar.setSizePolicy(sizePolicy)
        self.PBConfigurar.setObjectName("PBConfigurar")
        self.verticalLayout_3.addWidget(self.PBConfigurar)
        self.PBSearchSort = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PBSearchSort.sizePolicy().hasHeightForWidth())
        self.PBSearchSort.setSizePolicy(sizePolicy)
        self.PBSearchSort.setObjectName("PBSearchSort")
        self.verticalLayout_3.addWidget(self.PBSearchSort)
        spacerItem = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 1, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.PBOpen = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PBOpen.sizePolicy().hasHeightForWidth())
        self.PBOpen.setSizePolicy(sizePolicy)
        self.PBOpen.setText("")
        self.PBOpen.setObjectName("PBOpen")
        self.verticalLayout_4.addWidget(self.PBOpen)
        self.PBOpen_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PBOpen_2.sizePolicy().hasHeightForWidth())
        self.PBOpen_2.setSizePolicy(sizePolicy)
        self.PBOpen_2.setText("")
        self.PBOpen_2.setObjectName("PBOpen_2")
        self.verticalLayout_4.addWidget(self.PBOpen_2)
        self.gridLayout.addLayout(self.verticalLayout_4, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(457, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.PBAdicionar = QtWidgets.QPushButton(self.centralwidget)
        self.PBAdicionar.setObjectName("PBAdicionar")
        self.gridLayout_3.addWidget(self.PBAdicionar, 0, 0, 1, 1)
        self.PBFechar = QtWidgets.QPushButton(self.centralwidget)
        self.PBFechar.setObjectName("PBFechar")
        self.gridLayout_3.addWidget(self.PBFechar, 0, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(168, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 0, 2, 1, 1)
        self.PBRemover = QtWidgets.QPushButton(self.centralwidget)
        self.PBRemover.setObjectName("PBRemover")
        self.gridLayout_3.addWidget(self.PBRemover, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 3, 0, 1, 2)
        self.TVFiles = QtWidgets.QTableWidget(self.centralwidget)
        self.TVFiles.setObjectName("TVFiles")
        self.TVFiles.setColumnCount(0)
        self.TVFiles.setRowCount(0)
        self.gridLayout.addWidget(self.TVFiles, 0, 0, 2, 1)
        self.TVFiles.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "File Mx Cloud Beta"))
        self.PBConfigurar.setText(_translate("MainWindow", "Configurar"))
        self.PBSearchSort.setText(_translate("MainWindow", "Pesquisar / Organizar"))
        self.PBAdicionar.setText(_translate("MainWindow", "Adicionar"))
        self.PBFechar.setText(_translate("MainWindow", "Fechar"))
        self.PBRemover.setText(_translate("MainWindow", "Remover"))

